from datetime import datetime, timedelta
import pandas as pd
import os


def carregar_dados (caminho_arquivo):
    """Carrega dados de um arquivo CSV."""
    return pd.read_csv(caminho_arquivo)

def transform (df, columns_to_fill):
    """Preenche valores vazios nas colunas especificadas usando forward fill."""
    for coluna in columns_to_fill:
        df [coluna] = df.groupby('id') [coluna].fillna(method = 'ffill')


def criar_coluna_mesclada (df, columns_to_merge, new_column_name):
    """Cria uma nova coluna mesclando valores de outras colunas."""

    def merge_and_clean (row):
        merged = '|'.join(str(val) for val in row if pd.notna(val))
        return merged.strip()

    df [new_column_name] = df [columns_to_merge].apply(merge_and_clean, axis = 1)


def calcular_idade (data_nascimento):
    """Calcula a idade com base na data de nascimento."""
    hoje = datetime.now()
    return hoje.year - data_nascimento.year - ((hoje.month, hoje.day) < (data_nascimento.month, data_nascimento.day))


def split_admissions (admissions):
    """Divide internamentos que atravessam o final do mês e ajusta a coluna 'data_ajustada'."""
    new_admissions = []
    for _, admission in admissions.iterrows():
        start_date = admission ['data_internamento']
        end_date = admission ['data_hora_final']
        if pd.isna(start_date) or pd.isna(end_date):
            admission ['data_ajustada'] = None  # Garante que a coluna seja atualizada
            new_admissions.append(admission.to_dict())
            continue
        if start_date.month != end_date.month:
            # Determinar o último dia do mês
            last_day_of_month = (start_date.replace(day = 28) + timedelta(days = 4)).replace(day = 1) - timedelta(
                days = 1)
            # Criar a primeira parte do internamento
            first_part = admission.to_dict()
            first_part ['data_internamento'] = start_date.strftime('%Y-%m-%d %H:%M')
            first_part ['data_hora_final'] = last_day_of_month.strftime('%Y-%m-%d %H:%M')
            first_part ['data_ajustada'] = (last_day_of_month - start_date).days
            new_admissions.append(first_part)
            # Criar a segunda parte do internamento
            second_part = admission.to_dict()
            second_part ['data_internamento'] = (last_day_of_month + timedelta(days = 1)).strftime('%Y-%m-%d %H:%M')
            second_part ['data_hora_final'] = end_date.strftime('%Y-%m-%d %H:%M')
            second_part ['data_ajustada'] = (end_date - (last_day_of_month + timedelta(days = 1))).days
            new_admissions.append(second_part)
        else:
            # Caso o internamento não atravesse o final do mês
            admission ['data_ajustada'] = (end_date - start_date).days
            new_admissions.append(admission.to_dict())
    # Criar DataFrame final
    result = pd.DataFrame(new_admissions)
    # Incrementar 1 nos valores da coluna 'data_ajustada'
    result ['data_ajustada'] += 1
    return result


def preencher_data_hora_final (df):
    """Preenche valores NaN na coluna 'data_hora_final' com a data atual (sem horas) se 'data_internamento' estiver preenchida."""
    # Obtendo apenas a data atual, sem horas
    data_atual = pd.to_datetime(datetime.now().strftime('%Y-%m-%d'))
    # Garantindo que 'data_internamento' esteja no formato datetime
    df ['data_internamento'] = pd.to_datetime(df ['data_internamento'], errors = 'coerce')
    # Garantindo que 'data_hora_final' esteja no formato datetime
    df ['data_hora_final'] = pd.to_datetime(df ['data_hora_final'], errors = 'coerce')
    # Preenchendo 'data_hora_final' com a data atual, caso 'data_internamento' esteja preenchida e 'data_hora_final' esteja vazia
    df ['data_hora_final'] = df.apply(
        lambda row:data_atual if pd.notnull(row ['data_internamento']) and pd.isnull(row ['data_hora_final']) else row [
            'data_hora_final'],
        axis = 1
    )


def calcular_data_ajustada (df):
    """Cria uma nova coluna 'data_ajustada' com a diferença em dias entre 'data_hora_final' e 'data_internamento'."""
    # Garantindo que 'data_internamento' e 'data_hora_final' estejam no formato datetime
    df ['data_internamento'] = pd.to_datetime(df ['data_internamento'], errors = 'coerce')
    df ['data_hora_final'] = pd.to_datetime(df ['data_hora_final'], errors = 'coerce')
    # Calculando a diferença entre 'data_hora_final' e 'data_internamento' e convertendo para dias
    df ['data_ajustada'] = (df ['data_hora_final'] - df ['data_internamento']).dt.days


def renomear_colunas_e_salvar (arquivo_entrada, arquivo_saida, exclusao_colunas = None):
    """Renomeia colunas, trata os dados e salva em um novo arquivo CSV."""

    caminho_base = os.path.dirname(os.path.abspath(__file__))

    caminho_entrada = os.path.join(caminho_base, arquivo_entrada)
    caminho_saida = os.path.join(caminho_base, arquivo_saida)

    df = pd.read_csv(caminho_entrada)

    colunas_a_preencher = ['uti_inc', 'uti_vita', 'uti_santa_casa', 'uti_im', 'uti_nacoes', 'uti_sao_rafael', 'uti_hr',
                           'uti_hsl']

    for coluna in colunas_a_preencher:
        if coluna not in df.columns:
            print(f"A coluna '{coluna}' não existe no DataFrame. Verifique as colunas a serem preenchidas.")
            return

    novo_nome_colunas = {

        'grupos___1': 'grupo_neurologico',
        'grupos___2': 'grupo_respiratorio',
        'grupos___3': 'grupo_cardiovascular_hemodinamico',
        'grupos___4': 'grupo_abdominal',
        'grupos___5': 'grupo_endocrino_metabolico_hidroeletrolitico',
        'grupos___6': 'grupo_renal_urologia',
        'grupos___7': 'grupo_hematologia',
        'grupos___8': 'grupo_sepse_choque_septico',
        'grupos___9': 'grupo_trauma',
        'grupos___10': 'grupo_cabeça_pescoço_ortopedia',
        'grupos___11': 'grupo_ginecologia_obstetricia',
        'grupos___12': 'grupo_intoxicaçao_exogena',
        'sub_grupo_neurologico___1': 'sub_avc',
        'sub_grupo_neurologico___2': 'sub_neuro_infecçao',
        'sub_grupo_neurologico___3': 'sub_hsa',
        'sub_grupo_neurologico___4': 'sub_hsd',
        'sub_grupo_neurologico___5': 'sub_hed',
        'sub_grupo_neurologico___6': 'sub_crise_convulsiva_epilepsia',
        'sub_grupo_neurologico___7': 'sub_trombose_venosa_snc',
        'sub_grupo_neurologico___8': 'sub_neuro_neoplasia',
        'sub_grupo_neurologico___9': 'sub_neuromuscular',
        'sub_grupo_neurologico___10': 'sub_delirium',
        'sub_grupo_neurologico___11': 'sub_encefalopatia_nao_especifica_rnc',
        'sub_grupo_neurologico___12': 'sub_lesao_hipoxico_isquemica_pos_pcr',
        'sub_grupo_neurologico___13': 'sub_lesao_medular',
        'sub_grupo_neurologico___14': 'sub_epilepsia',
        'sub_grupo_neurologico___15': 'pos_operatorio',
        'sub_grupo_neurologico___16': 'sub_neuro_outros',
        'sub_grupo_respiratorio___1': 'sub_respiratorio_infecçao',
        'sub_grupo_respiratorio___2': 'sub_dpoc_descompensado',
        'sub_grupo_respiratorio___3': 'sub_asma_descompensada',
        'sub_grupo_respiratorio___4': 'sub_sara',
        'sub_grupo_respiratorio___5': 'sub_broncoaspiraçao',
        'sub_grupo_respiratorio___6': 'sub_lesao_pleural',
        'sub_grupo_respiratorio___7': 'sub_edema_de_glote',
        'sub_grupo_respiratorio___8': 'sub_atelectasia',
        'sub_grupo_respiratorio___9': 'sub_tep',
        'sub_grupo_respiratorio___10': 'sub_eap_edema_agudo_hipertensivo_congestao_pulmonar',
        'sub_grupo_respiratorio___11': 'sub_hemoptise',
        'sub_grupo_respiratorio___12': 'sub_insuficiencia_respiratoria_de_cause_neuromuscular',
        'sub_grupo_respiratorio___13': 'sub_pos_operatorio_toracico',
        'sub_grupo_respiratorio___14': 'sub_respiratorio_outros',
        'sub_grupo_cardiovascular___1': 'sub_isquemia_miocardica',
        'sub_grupo_cardiovascular___2': 'sub_insuficiencia_cardiaca',
        'sub_grupo_cardiovascular___3': 'sub_arritmias',
        'sub_grupo_cardiovascular___4': 'sub_doenças_da_aorta',
        'sub_grupo_cardiovascular___5': 'sub_oclusao_arterial',
        'sub_grupo_cardiovascular___6': 'sub_tvp',
        'sub_grupo_cardiovascular___7': 'sub_pos_pcr_de_causa_indefinida',
        'sub_grupo_cardiovascular___8': 'sub_pos_operatorio_cardiovascular',
        'sub_grupo_cardiovascular___9': 'sub_tamponamento_cardiaco',
        'sub_grupo_cardiovascular___10': 'sub_choque_cardiogenico',
        'sub_grupo_cardiovascular___11': 'sub_cardiovascular_outros',
        'sub_grupo_abdominal___1': 'sub_abdomen_agudo',
        'sub_grupo_abdominal___2': 'sub_geca',
        'sub_grupo_abdominal___3': 'sub_hemorragia_digestiva',
        'sub_grupo_abdominal___4': 'sub_hepatologia',
        'sub_grupo_abdominal___5': 'sub_pos_operatorio_eletivo_de_cirurgia_abdominal',
        'sub_grupo_endocrino___1': 'sub_disturbio_eletrolitico',
        'sub_grupo_endocrino___2': 'sub_cetoacidose_diabetica',
        'sub_grupo_endocrino___3': 'sub_estado_hiperosmolar',
        'sub_grupo_endocrino___4': 'sub_crise_tireotoxica',
        'sub_grupo_endocrino___5': 'sub_endocrino_metabolico_outros',
        'sub_grupo_renal_urulogia___1': 'sub_renal_urologia_infecçao',
        'sub_grupo_renal_urulogia___2': 'sub_ira',
        'sub_grupo_renal_urulogia___3': 'sub_rabdomiolise',
        'sub_grupo_renal_urulogia___4': 'sub_nefrolitiase',
        'sub_grupo_renal_urulogia___5': 'sub_renal_urologia_pos_operatorio',
        'sub_grupo_hematologia___1': 'sub_anemia',
        'sub_grupo_hematologia___2': 'sub_plaquetopenia',
        'sub_grupo_hematologia___3': 'sub_neutropenia',
        'sub_grupo_hematologia___4': 'sub_pancitopenia',
        'sub_grupo_hematologia___5': 'sub_leucemia_linfoma',
        'sub_grupo_hematologia___6': 'sub_disturbios_da_coagulaçao',
        'sub_grupo_hematologia___7': 'sub_hematologia_outros',
        'sub_grupo_sepse_foco___1': 'sub_sepse_foco_neurologico',
        'sub_grupo_sepse_foco___2': 'sub_respiratorio',
        'sub_grupo_sepse_foco___3': 'sub_abdominal',
        'sub_grupo_sepse_foco___4': 'sub_urinario',
        'sub_grupo_sepse_foco___5': 'sub_corrente_sanguinea',
        'sub_grupo_sepse_foco___6': 'sub_partes_moles',
        'sub_grupo_sepse_foco___7': 'sub_sepse_foco_indeterminado',
        'sub_grupo_sepse_foco___8': 'sub_sepse_foco_outros',
        'sub_grupo_sepse_disfuncao___1': 'sub_sepse_disfuncao_neurologico',
        'sub_grupo_sepse_disfuncao___2': 'sub_respiratorio',
        'sub_grupo_sepse_disfuncao___3': 'sub_hemodinamica',
        'sub_grupo_sepse_disfuncao___4': 'sub_renal',
        'sub_grupo_sepse_disfuncao___5': 'sub_plaquetopenia',
        'sub_grupo_sepse_disfuncao___6': 'sub_hiperbilirrubinemia',
        'sub_grupo_trauma_lesao___1': 'sub_tce',
        'sub_grupo_trauma_lesao___2': 'sub_trm',
        'sub_grupo_trauma_lesao___3': 'sub_fx_vertebral_sem_trm',
        'sub_grupo_trauma_lesao___4': 'sub_face_cervical',
        'sub_grupo_trauma_lesao___5': 'sub_cardiaca',
        'sub_grupo_trauma_lesao___6': 'sub_toracica',
        'sub_grupo_trauma_lesao___7': 'sub_abdominal_pelvico',
        'sub_grupo_trauma_lesao___8': 'sub_extremidades',
        'sub_grupo_trauma_lesao___9': 'sub_embolia_gordurosa',
        'sub_grupo_trauma_mecanismo___1': 'sub_colisoes',
        'sub_grupo_trauma_mecanismo___2': 'sub_queda_de_outro_nivel',
        'sub_grupo_trauma_mecanismo___3': 'sub_queda_de_mesmo_nivel',
        'sub_grupo_trauma_mecanismo___4': 'sub_atropelamento',
        'sub_grupo_trauma_mecanismo___5': 'sub_agressao_faf_fab',
        'sub_grupo_trauma_mecanismo___6': 'sub_queimaduras_choque_eletrico',
        'sub_grupo_trauma_mecanismo___7': 'sub_lesao_autoinfligida',
        'sub_grupo_cabeca_ortopedia___1': 'sub_pos_operatorio_cabeça_e_pescoço',
        'sub_grupo_cabeca_ortopedia___2': 'sub_pos_operatorio_eletivo_ortopedia',
        'sub_grupo_ginecologia___1': 'sub_sindrome_hellp',
        'sub_grupo_ginecologia___2': 'sub_pre_eclampsia',
        'sub_grupo_ginecologia___3': 'sub_eclampsia',
        'sub_grupo_ginecologia___4': 'sub_embolia_de_liquido_amniotico',
        'sub_grupo_ginecologia___5': 'sub_deslocamento_prematuro_de_placenta',
        'sub_grupo_ginecologia___6': 'sub_esteatose_hepatica_da_gestaçao',
        'sub_grupo_ginecologia___7': 'sub_diabetes_gestacional',
        'sub_grupo_ginecologia___8': 'sub_civd',
        'sub_grupo_ginecologia___9': 'sub_cirurgias_ginecologicas',
        'sub_grupo_ginecologia___10': 'sub_ginecologia_outros',
        'sub_grupo_intoxicacao_exogena___1': 'sub_ansiolitico',
        'sub_grupo_intoxicacao_exogena___2': 'sub_antidepressivos',
        'sub_grupo_intoxicacao_exogena___3': 'sub_antipsicoticos',
        'sub_grupo_intoxicacao_exogena___4': 'sub_alcool',
        'sub_grupo_intoxicacao_exogena___5': 'sub_drogas_ilicitas',
        'sub_grupo_intoxicacao_exogena___6': 'sub_organofosforados',
        'sub_grupo_intoxicacao_exogena___7': 'sub_intoxicacao_exogena_outros',
        'especificos_neuro_infeccao___1': 'especificos_neuro_Meningite',
        'especificos_neuro_infeccao___2': 'especificos_neuro_Encefalite',
        'especificos_neuro_infeccao___3': 'especificos_neuro_Ventriculite',
        'especificos_neuro_infeccao___4': 'especificos_neuro_Abscesso',
        'especificos_neuro_infeccao___5': 'especificos_neuro_infecçao_outros',
        'especificos_neuro_delirium___1': 'especificos_neuro_Hipoativo',
        'especificos_neuro_delirium___2': 'especificos_neuro_Hiperativo',
        'especificos_neuro_encefalopatia___1': 'renal_(rnc)',
        'especificos_neuro_encefalopatia___2': 'hepatica_(rnc)',
        'especificos_neuro_po___1': 'especifico_neuro_neoplasia',
        'especificos_neuro_po___2': 'especifico_neuro_coluna',
        'especificos_neuro_po___3': 'especifico_neuro_vascular_inclui_carotidas',
        'especificos_neuro_po___4': 'especifico_neuro_epilepsia',
        'especificos_neuro_po___5': 'especifico_neuro_hidrocefalia',
        'especificos_neuro_po___6': 'especifico_neuro_hic_cirurgia_descompressiva_ou_dve',
        'especificos_neuro_po___7': 'especifico_neuro_po_outros',
        'especificos_resp_infeccao___1': 'especificos_resp_pneumonia_comunitaria',
        'especificos_resp_infeccao___2': 'especificos_resp_pneumonia_nosocomial',
        'especificos_resp_infeccao___3': 'especificos_resp_dpco_exacerbado_por_infecçao',
        'especificos_resp_infeccao___4': 'especificos_resp_pneumonite_viral_',
        'especificos_resp_infeccao___5': 'especificos_resp_traqueobronquite',
        'especificos_resp_infeccao___6': 'especificos_resp_empiema',
        'especificos_resp_infeccao___7': 'especificos_resp_infecçao_outros',
        'especificos_resp_lesao_pleural___1': 'especificos_resp_derrame_pleural',
        'especificos_resp_lesao_pleural___2': 'especificos_resp_hemotorax',
        'especificos_resp_lesao_pleural___3': 'especificos_resp_pneumotorax',
        'especificos_resp_po_toracico___1': 'especificos_resp_toracotomia',
        'especificos_resp_po_toracico___2': 'especificos_resp_videotoracoscopia',
        'especificos_resp_po_toracico___3': 'especificos_resp_traqueostomia',
        'especificos_resp_po_toracico___4': 'especificos_resp_po_toracico_outros',
        'espec_cardio_po___1': 'espec_cardio_rmv',
        'espec_cardio_po___2': 'espec_cardio_valvar',
        'espec_cardio_po___3': 'espec_cardio_angioplastia',
        'espec_cardio_po___4': 'espec_cardio_vascular_aberta',
        'espec_cardio_po___5': 'espec_cardio_endovascular',
        'espec_cardio_po___6': 'espec_cardio_transplante_cardiaco',
        'espec_cardio_po_valvar___1': 'espec_cardio_mitral',
        'espec_cardio_po_valvar___2': 'espec_cardio_aortica',
        'espec_cardio_po_valvar___3': 'espec_cardio_tricuspide',
        'espec_abdominal_abd_agudo___1': 'espec_abdominal_pancreatite',
        'espec_abdominal_abd_agudo___2': 'espec_abdominal_vias_biliares',
        'espec_abdominal_abd_agudo___3': 'espec_abdominal_apendice',
        'espec_abdominal_abd_agudo___4': 'espec_abdominal_diverticulite',
        'espec_abdominal_abd_agudo___5': 'espec_abdominal_outros_inflamatorio_infeccioso',
        'espec_abdominal_abd_agudo___6': 'espec_abdominal_perfurativo',
        'espec_abdominal_abd_agudo___7': 'espec_abdominal_oclusivo',
        'espec_abdominal_abd_agudo___8': 'espec_abdominal_isquemia_mesenterica',
        'espec_abdominal_abd_agudo___9': 'espec_abdominal_abd_agudo_outros',
        'espec_abd_hemorragia_digestiva___1': 'espec_and_hemorragia_hda',
        'espec_abd_hemorragia_digestiva___2': 'espec_and_hemorragia_hdb',
        'espec_abdominal_hepatologia___1': 'espec_abdominal_cirrose_hepatica',
        'espec_abdominal_hepatologia___2': 'espec_abdominal_hepatite_aguda',
        'espec_abdominal_hepatologia___3': 'espec_abdominal_insuficiencia_hepatica_aguda',
        'espec_endocrino_disturbio_eletro___1': 'espec_endocrino_hiponatremia',
        'espec_endocrino_disturbio_eletro___2': 'espec_endocrino_hipernatremia',
        'espec_endocrino_disturbio_eletro___3': 'espec_endocrino_hipercalemia',
        'espec_endocrino_disturbio_eletro___4': 'espec_endocrino_hipocalemia',
        'espec_endocrino_disturbio_eletro___5': 'espec_endocrino_disturbio_eletro_outros',
        'espec_renal_infeccao___1': 'espec_renal_cistite',
        'espec_renal_infeccao___2': 'espec_renal_pielonefrite',
        'espec_renal_po___1': 'espec_renal_po_transplante_renal',
        'espec_renal_po___2': 'espec_renal_po_nefrectomia',
        'espec_renal_po___3': 'espec_renal_po_implante_de_duplo_j',
        'espec_renal_po___4': 'espec_renal_po_nefrostomia',
        'espec_renal_po___5': 'espec_renal_po_cistostomia',
        'espec_renal_po___6': 'espec_renal_po_prostatectomia',
        'espec_renal_po___7': 'espec_renal_po_neoplasias_renal_neoplasias_renal_bexiga',
        'espec_sepse_disf_hemodinamica___1': 'espec_hemodinamica_hiperlactatemia',
        'espec_sepse_disf_hemodinamica___2': 'espec_hemodinamica_choque',
        'espec_trauma_lesao_tce___1': 'espec_lesão_tce_contusão',
        'espec_trauma_lesao_tce___2': 'espec_lesão_tce_hemorragia_intraparenquimatosa',
        'espec_trauma_lesao_tce___3': 'espec_lesão_tce_hsa_traumatica',
        'espec_trauma_lesao_tce___4': 'espec_lesão_tce_hed',
        'espec_trauma_lesao_tce___5': 'espec_lesão_tce_hsd',
        'espec_trauma_lesao_tce___6': 'espec_lesão_tce_lad',
        'espec_trauma_lesao_tce___7': 'espec_lesão_tce_hic',
        'espec_trauma_lesao_tce___8': 'espec_lesão_tce_dve_intraparenquimatosa',
        'espec_trauma_lesao_tce___9': 'espec_lesão_tce_pic',
        'espec_trauma_lesao_tce___10': 'espec_lesão_tce_craniectomia_descompressiva',
        'espec_trauma_lesao_tce___11': 'espec_lesão_tce_bulbo_jugular',
        'espec_trauma_lesao_tce___12': 'espec_trauma_lesão_tce_outros',
        'espec_trauma_lesao_face_cervical___1': 'espec_face_cervical_vascular',
        'espec_trauma_lesao_face_cervical___2': 'espec_face_cervical_traqueia',
        'espec_trauma_lesao_face_cervical___3': 'espec_face_cervical_esofagia',
        'espec_trauma_lesao_face_cervical___4': 'espec_face_cervical_fratura_lesao_face',
        'espec_trauma_lesao_face_cervical___5': 'espec_trauma_lesao_face_cervical_outros',
        'espec_trauma_lesao_cardiaca___1': 'espec_lesao_cardiaca_contusao',
        'espec_trauma_lesao_cardiaca___2': 'espec_lesao_cardiaca_tamponamento',
        'espec_trauma_lesao_cardiaca___3': 'espec_trauma_lesao_cardiaca_outros',
        'espec_trauma_lesao_toracica___1': 'espec_lesao_toracica_hemotorax',
        'espec_trauma_lesao_toracica___2': 'espec_lesao_toracica_pneumotorax',
        'espec_trauma_lesao_toracica___7': 'espec_lesao_toracica_contusao',
        'espec_trauma_lesao_toracica___3': 'espec_lesao_toracica_fraturas_arcos_costais',
        'espec_trauma_lesao_toracica___4': 'espec_lesao_toracica_lesoes_mediastinais',
        'espec_trauma_lesao_toracica___5': 'espec_lesao_toracica_vascular_grandes_vasos',
        'espec_trauma_lesao_toracica___6': 'espec_lesao_toracica_controle_de_danos_toracicos',
        'espec_trauma_lesao_toracica___8': 'espec_trauma_lesao_toracica_outros',
        'espec_trauma_lesao_abd_pelvico___1': 'espec_abd_pelvico_fratura_pelve',
        'espec_trauma_lesao_abd_pelvico___2': 'espec_abd_pelvico_hepatica',
        'espec_trauma_lesao_abd_pelvico___3': 'espec_abd_pelvico_esplenica',
        'espec_trauma_lesao_abd_pelvico___4': 'espec_abd_pelvico_renal',
        'espec_trauma_lesao_abd_pelvico___5': 'espec_abd_pelvico_retroperitoneal',
        'espec_trauma_lesao_abd_pelvico___6': 'espec_abd_pelvico_vascular',
        'espec_trauma_lesao_abd_pelvico___7': 'espec_abd_pelvico_gastrointestinal',
        'espec_trauma_lesao_abd_pelvico___8': 'espec_abd_pelvico_controle_de_danos_abdominais',
        'espec_trauma_lesao_abd_pelvico___9': 'espec_abd_pelvico_peritoniostomia',
        'espec_trauma_lesao_abd_pelvico___10': 'espec_abd_pelvico_sindrome_compartimental_abdominal',
        'espec_trauma_lesao_abd_pelvico___11': 'espec_trauma_lesao_abd_pelvico_outros',
        'espec_trauma_lesao_extremidades___1': 'espec_lesao_extremidades_femur',
        'espec_trauma_lesao_extremidades___2': 'espec_lesao_extremidades_membros_inferiores_nao_femur',
        'espec_trauma_lesao_extremidades___3': 'espec_lesao_extremidades_membros_superiores',
        'espec_trauma_lesao_extremidades___4': 'espec_lesao_extremidades_neurovascular',
        'espec_trauma_lesao_extremidades___5': 'espec_lesao_extremidades_controle_de_danos_de_extremidades',
        'espec_trauma_lesao_extremidades___6': 'espec_lesao_extremidades_sindrome_comportamental_de_extremidades',
        'espec_trauma_lesao_extremidades___7': 'espec_trauma_lesao_extremidades_outros',
        'tipo_do_choque___1': 'tipo_do_choque_hipovolemico_hemorragico',
        'tipo_do_choque___2': 'tipo_do_choque_distributivo_inflamatorio',
        'tipo_do_choque___3': 'tipo_do_choque_distributivo_anafilatico',
        'tipo_do_choque___4': 'tipo_do_choque_distributivo_neurogenico',
        'tipo_do_choque___5': 'tipo_do_choque_obstrutivo_tep_maciço',
        'tipo_do_choque___6': 'tipo_do_choque_obstrutivo_tamponamento_cardíaco',
        'tipo_do_choque___7': 'tipo_do_choque_obstrutivo_pneumotórax',
        'tipo_do_choque___8': 'tipo_do_choque_cardiogenico',
        'principais_comorbidades___1': 'principais_comorbidades_diabetes_mellitus',
        'principais_comorbidades___2': 'principais_comorbidades_hipertensão_essencial',
        'principais_comorbidades___3': 'principais_comorbidades_dislipidemia',
        'principais_comorbidades___4': 'principais_comorbidades_avc_isquêmico_prévio',
        'principais_comorbidades___5': 'principais_comorbidades_infarto_agudo_do_miocárdio_prévio',
        'principais_comorbidades___6': 'principais_comorbidades_doença_arterial_coronariana_relatada_prévia',
        'principais_comorbidades___7': 'principais_comorbidades_dpoc',
        'principais_comorbidades___8': 'principais_comorbidades_hipotireoidismo',
        'principais_comorbidades___9': 'principais_comorbidades_ic_fe_reduzido',
        'principais_comorbidades___10': 'principais_comorbidades_ic_fe_preservada',
        'principais_comorbidades___11': 'principais_comorbidades_drc_dialitica',
        'principais_comorbidades___12': 'principais_comorbidades_drc_nao_dialitica',
        'principais_comorbidades___14': 'principais_comorbidades_doença_psiquiátrica',
        'principais_comorbidades___15': 'principais_comorbidades_etilismo',
        'principais_comorbidades___16': 'principais_comorbidades_tabagismo',
        'principais_comorbidades___17': 'principais_comorbidades_drogadiçao',
        'principais_comorbidades___18': 'principais_comorbidades_hiv',
        'principais_comorbidades___19': 'principais_comorbidades_obesidade',
        'principais_comorbidades___13': 'principais_comorbidades_outras',
        'doenca_psiquiatrica___1': 'doenca_psiquiatrica_transtorno_de_bipolaridade',
        'doenca_psiquiatrica___2': 'doenca_psiquiatrica_tanstorno_de_ansiedade_generalizada',
        'doenca_psiquiatrica___3': 'doenca_psiquiatrica_depressao',
        'doenca_psiquiatrica___4': 'doenca_psiquiatrica_esquizofrenia',
        'doenca_psiquiatrica___5': 'doenca_psiquiatrica_sindrome_do_panico',
        'doenca_psiquiatrica___6': 'doenca_psiquiatrica_borderline',
        'grupo_comorbidade___1': 'grupo_comorbidade_neurologico',
        'grupo_comorbidade___2': 'grupo_comorbidade_respiratorio',
        'grupo_comorbidade___3': 'grupo_comorbidade_cardiovascular',
        'grupo_comorbidade___4': 'grupo_comorbidade_abdominal',
        'grupo_comorbidade___5': 'grupo_comorbidade_renal',
        'grupo_comorbidade___6': 'grupo_comorbidade_endocrino',
        'grupo_comorbidade___7': 'grupo_comorbidade_reumatologico',
        'grupo_comorbidade___8': 'grupo_comorbidade_neoplasico',
        'grupo_comorbidade___9': 'grupo_comorbidade_hematologico',
        'lista_comorbidades_neuro___1': 'comorbidades_neuro_parkinson',
        'lista_comorbidades_neuro___2': 'comorbidades_neuro_alzheimer',
        'lista_comorbidades_neuro___3': 'comorbidades_neuro_demencia',
        'lista_comorbidades_neuro___4': 'comorbidades_neuro_outras_sequelas_neurologicas_epilepsia',
        'lista_comorbidades_neuro___5': 'comorbidades_neuro_doenças_neuromuscular',
        'lista_comorbidades_neuro___6': 'comorbidades_neuro_epilepsia',
        'lista_comorbidades_neuro___7': 'comorbidades_neuro_paraplegia_ou_tetraplegia',
        'lista_comorbidades_neuro___8': 'comorbidades_neuro_outros',
        'lista_comorbidades_resp___1': 'comorbidades_resp_bronquiectasia',
        'lista_comorbidades_resp___2': 'comorbidades_resp_asma',
        'lista_comorbidades_resp___3': 'comorbidades_resp_outros',
        'lista_cardio_hemodinamico___1': 'cardio_hemodinamico_arritmia',
        'lista_cardio_hemodinamico___2': 'cardio_hemodinamico_aneurisma_de_aorta',
        'lista_cardio_hemodinamico___3': 'cardio_hemodinamico_doença_arterial_periferica',
        'lista_cardio_hemodinamico___4': 'cardio_hemodinamico_doença_venosa_cronica',
        'lista_cardio_hemodinamico___5': 'cardio_hemodinamico_outros',
        'lista_comorbidades_abdominal___1': 'comorbidades_abdominal_doença_diverticular',
        'lista_comorbidades_abdominal___2': 'comorbidades_abdominal_litiase_biliar',
        'lista_comorbidades_abdominal___3': 'comorbidades_abdominal_pancreatopatia',
        'lista_comorbidades_abdominal___4': 'comorbidades_abdominal_doença_péptica',
        'lista_comorbidades_abdominal___5': 'comorbidades_abdominal_hepatopatia',
        'lista_comorbidades_abdominal___6': 'comorbidades_abdominal_outro',
        'lista_comorbidades_renal___1': 'comorbidades_renal_itu_de_repetiçao',
        'lista_comorbidades_renal___2': 'comorbidades_renal_outros',
        'lista_comorbidades_endocrino___1': 'comorbidades_endocrino_hipertireoidismo',
        'lista_comorbidades_endocrino___2': 'comorbidades_endocrino_outros',
        'lista_comorbidades_hemato___1': 'comorbidades_hemato_anemia_crônica',
        'lista_comorbidades_hemato___2': 'comorbidades_hemato_mielodisplagia',
        'lista_comorbidades_hemato___3': 'comorbidades_hemato_doença_tromboplaquetária',
        'lista_comorbidades_hemato___4': 'comorbidades_hemato_outros',
        'lista_comorbidades_reumato___1': 'comorbidades_reumato_artrite_reumatoide',
        'lista_comorbidades_reumato___2': 'comorbidades_reumato_saaf',
        'lista_comorbidades_reumato___3': 'comorbidades_reumato_lupus',
        'lista_comorbidades_reumato___4': 'comorbidades_reumato_outros',
        'neoplasia_localizacao___1': 'neoplasia_localizacao_snc',
        'neoplasia_localizacao___2': 'neoplasia_localizacao_cabeça_pescoço',
        'neoplasia_localizacao___3': 'neoplasia_localizacao_pulmao',
        'neoplasia_localizacao___4': 'neoplasia_localizacao_figado',
        'neoplasia_localizacao___5': 'neoplasia_localizacao_rins',
        'neoplasia_localizacao___6': 'neoplasia_localizacao_intestino',
        'neoplasia_localizacao___7': 'neoplasia_localizacao_gastrico',
        'neoplasia_localizacao___8': 'neoplasia_localizacao_esofago',
        'neoplasia_localizacao___9': 'neoplasia_localizacao_ginecologico_(inclui_mama)',
        'neoplasia_localizacao___10': 'neoplasia_localizacao_prostata',
        'neoplasia_localizacao___11': 'neoplasia_localizacao_hematologicos',
        'neoplasia_localizacao___12': 'neoplasia_localizacao_outros',
        'qual_procedimento_trauma___1': 'qual_procedimento_trauma_peritoniostomia',
        'qual_procedimento_trauma___2': 'qual_procedimento_trauma_controle_de_danos',
        'qual_procedimento_trauma___3': 'qual_procedimento_trauma_monitoramento_neurologico_avançado',
        'qual_procedimento_trauma___4': 'qual_procedimento_trauma_bypass_femoro_popliteo',
        'qual_procedimento_trauma___5': 'qual_procedimento_trauma_bypass_fibio_tibial',
        'qual_procedimento_trauma___6': 'qual_procedimento_trauma_bypass_ileo_inguinal',
        'qual_procedimento_trauma___7': 'qual_procedimento_trauma_bypass_popliteo_fibular',
        'qual_procedimento_trauma___8': 'qual_procedimento_trauma_bypass_popliteo_tibial',
        'qual_procedimento_trauma___9': 'qual_procedimento_trauma_cardiorrafia',
        'qual_procedimento_trauma___10': 'qual_procedimento_trauma_cervicotomia',
        'qual_procedimento_trauma___11': 'qual_procedimento_trauma_cistorrafia',
        'qual_procedimento_trauma___12': 'qual_procedimento_trauma_cistostomia',
        'qual_procedimento_trauma___13': 'qual_procedimento_trauma_colecistectomia',
        'qual_procedimento_trauma___14': 'qual_procedimento_trauma_colectomia',
        'qual_procedimento_trauma___15': 'qual_procedimento_trauma_colocação_de_filtro_de_veia_cava',
        'qual_procedimento_trauma___16': 'qual_procedimento_trauma_colorrafia',
        'qual_procedimento_trauma___17': 'qual_procedimento_trauma_craniectomia_descompressiva',
        'qual_procedimento_trauma___18': 'qual_procedimento_trauma_decorticação_pulmonar',
        'qual_procedimento_trauma___19': 'qual_procedimento_trauma_drenagem_de_hematoma_epidural',
        'qual_procedimento_trauma___20': 'qual_procedimento_trauma_drenagem_de_hematoma_intraparenquimatoso_cerebral',
        'qual_procedimento_trauma___21': 'qual_procedimento_trauma_drenagem_de_hematoma_subdural',
        'qual_procedimento_trauma___22': 'qual_procedimento_trauma_drenagem_de_hemopneumotórax',
        'qual_procedimento_trauma___23': 'qual_procedimento_trauma_drenagem_de_hemotórax',
        'qual_procedimento_trauma___24': 'qual_procedimento_trauma_drenagem_de_pneumotórax',
        'qual_procedimento_trauma___25': 'qual_procedimento_trauma_enterectomia',
        'qual_procedimento_trauma___26': 'qual_procedimento_trauma_enterorrafia',
        'qual_procedimento_trauma___27': 'qual_procedimento_trauma_esofagostomia',
        'qual_procedimento_trauma___28': 'qual_procedimento_trauma_esplenectomia',
        'qual_procedimento_trauma___29': 'qual_procedimento_trauma_fasciotomia',
        'qual_procedimento_trauma___30': 'qual_procedimento_trauma_fixaçao_da_clavicula',
        'qual_procedimento_trauma___31': 'qual_procedimento_trauma_Fixaçao_da_mao',
        'qual_procedimento_trauma___32': 'qual_procedimento_trauma_Fixaçao_de_braço',
        'qual_procedimento_trauma___33': 'qual_procedimento_trauma_fixaçao_de_coluna_cervical',
        'qual_procedimento_trauma___34': 'qual_procedimento_trauma_fixaçao_de_coluna_lombar',
        'qual_procedimento_trauma___35': 'qual_procedimento_trauma_fixaçao_de_coluna_toracica',
        'qual_procedimento_trauma___36': 'qual_procedimento_trauma_fixação_de_femur',
        'qual_procedimento_trauma___37': 'qual_procedimento_trauma_fixaçao_de_pelve',
        'qual_procedimento_trauma___38': 'qual_procedimento_trauma_fixaçao_de_perna',
        'qual_procedimento_trauma___39': 'qual_procedimento_trauma_fixaçao_do_pe',
        'qual_procedimento_trauma___40': 'qual_procedimento_trauma_frenorrafia',
        'qual_procedimento_trauma___41': 'qual_procedimento_trauma_gastroplastia',
        'qual_procedimento_trauma___42': 'qual_procedimento_trauma_gastrorrafia',
        'qual_procedimento_trauma___43': 'qual_procedimento_trauma_gatrostomia',
        'qual_procedimento_trauma___44': 'qual_procedimento_trauma_hepatectomia_parcial',
        'qual_procedimento_trauma___45': 'qual_procedimento_trauma_hepatorrafia',
        'qual_procedimento_trauma___46': 'qual_procedimento_trauma_hipotermia_induzida',
        'qual_procedimento_trauma___47': 'qual_procedimento_trauma_janela_pericardica',
        'qual_procedimento_trauma___48': 'qual_procedimento_trauma_jejunostomia',
        'qual_procedimento_trauma___49': 'qual_procedimento_trauma_	lobectomia_pulmonar',
        'qual_procedimento_trauma___50': 'qual_procedimento_trauma_nefrectomia',
        'qual_procedimento_trauma___51': 'qual_procedimento_trauma_nefrorrafia',
        'qual_procedimento_trauma___52': 'qual_procedimento_trauma_fancreatorrafia',
        'qual_procedimento_trauma___53': 'qual_procedimento_trauma_pneumorrafia',
        'qual_procedimento_trauma___54': 'qual_procedimento_trauma_rafia_de_vasos_intraabdominais',
        'qual_procedimento_trauma___55': 'qual_procedimento_trauma_rafia_de_vasos_intratoracicos',
        'qual_procedimento_trauma___56': 'qual_procedimento_trauma_toracotomia_ressucitadora',
        'qual_procedimento_trauma___57': 'qual_procedimento_trauma_outros_procedimentos_relacionados_ao_trauma',
        'controle_de_danos___1': 'controle_de_danos_vascular',
        'controle_de_danos___2': 'controle_de_danos_abdominal',
        'controle_de_danos___3': 'controle_de_danos_toracico',
        'controle_de_danos___4': 'controle_de_danos_pelvico',
        'controle_de_danos___5': 'controle_de_danos_cervical',
        'procedimento_neurologico_trauma___1': 'procedimento_neurologico_trauma_monitorização_da_pic',
        'procedimento_neurologico_trauma___2': 'procedimento_neurologico_trauma_bulbo_jugular',
        'procedimento_neurologico_trauma___3': 'procedimento_neurologico_trauma_ptio2',
        'qual_procedimento_utilizado___3': 'procedimento_utilizado_sondagem_vesical_de_demora',
        'qual_procedimento_utilizado___4': 'procedimento_utilizado_sondagem_vesical_de_alivio',
        'qual_procedimento_utilizado___5': 'procedimento_utilizado_sondagem_enteral',
        'qual_procedimento_utilizado___1': 'procedimento_utilizado_acesso_venoso_central',
        'qual_procedimento_utilizado___2': 'procedimento_utilizado_intubação_orotraqueal',
        'qual_procedimento_utilizado___6': 'procedimento_utilizado_suporte_ventilatorio',
        'qual_procedimento_utilizado___7': 'procedimento_utilizado_punção_de_artéria_radial',
        'qual_procedimento_utilizado___8': 'procedimento_utilizado_punção_de_arteria_femoral',
        'qual_procedimento_utilizado___18': 'procedimento_utilizado_punção_lombar',
        'qual_procedimento_utilizado___9': 'procedimento_utilizado_hemodialise',
        'qual_procedimento_utilizado___16': 'procedimento_utilizado_traqueostomia',
        'qual_procedimento_utilizado___12': 'procedimento_utilizado_cardioversao',
        'qual_procedimento_utilizado___13': 'procedimento_utilizado_marcapasso_transvenoso',
        'qual_procedimento_utilizado___11': 'procedimento_utilizado_cateter_de_swan_ganz',
        'qual_procedimento_utilizado___19': 'procedimento_utilizado_outro_dispositivo_de_monitorizaçao_hemo',
        'qual_procedimento_utilizado___10': 'procedimento_utilizado_balao_intra_aortico',
        'qual_procedimento_utilizado___14': 'procedimento_utilizado_dve',
        'qual_procedimento_utilizado___20': 'procedimento_utilizado_monitorizaçao_da_pic_continua',
        'qual_procedimento_utilizado___15': 'procedimento_utilizado_dvp',
        'qual_procedimento_utilizado___21': 'procedimento_utilizado_paracentese_abdominal',
        'qual_procedimento_utilizado___22': 'procedimento_utilizado_pericardiocentese',
        'qual_procedimento_utilizado___23': 'procedimento_utilizado_hipotermia_induzida_pos_pcr',
        'qual_procedimento_utilizado___24': 'procedimento_utilizado_ecmo_va',
        'qual_procedimento_utilizado___17': 'procedimento_utilizado_outros_procedimentos',
        'sitio_puncao___1': 'sitio_puncao_jugular_direita',
        'sitio_puncao___2': 'sitio_puncao_jugular_esquerda',
        'sitio_puncao___3': 'sitio_puncao_subclavia_direita',
        'sitio_puncao___4': 'sitio_puncao_subclavia_esquerda',
        'sitio_puncao___5': 'sitio_puncao_femoral_direita',
        'sitio_puncao___6': 'sitio_puncao_femoral_esquerda',
        'cardioversao___1': 'cardioversao_cardioversao_eletrica_de_emergencia',
        'cardioversao___2': 'cardioversao_cardioversao_quimica_de_arritmia_paroxista_em_emergencia',
        'procedimento_suporte_ventilatorio___1': 'procedimento_suporte_ventilatorio_vm',
        'procedimento_suporte_ventilatorio___2': 'procedimento_suporte_ventilatorio_vni',
        'procedimento_suporte_ventilatorio___3': 'procedimento_suporte_ventilatorio_ecmo_vv',
        'procedimento_suporte_ventilatorio___4': 'procedimento_suporte_ventilatorio_oxigenioterapia',
        'identificada_infeccao___1': 'identificada_infeccao_sistema_nervoso_central_(SNC)',
        'identificada_infeccao___2': 'identificada_infeccao_pulmonar',
        'identificada_infeccao___3': 'identificada_infeccao_corrente_sanguinea',
        'identificada_infeccao___4': 'identificada_infeccao_abdominal',
        'identificada_infeccao___5': 'identificada_infeccao_urinario',
        'identificada_infeccao___6': 'identificada_infeccao_partes_moles',
        'identificada_infeccao___7': 'identificada_infeccao_foco_indeterminado',
        'tipos_bacterias___1': 'tipos_bacterias_staphylococcus_aureus',
        'tipos_bacterias___2': 'tipos_bacterias_enterococcus_faecalis',
        'tipos_bacterias___3': 'tipos_bacterias_klebsiella_pneumoniae',
        'tipos_bacterias___4': 'tipos_bacterias_pseudomonas_aeruginosa',
        'tipos_bacterias___5': 'tipos_bacterias_escherichia_coli',
        'tipos_bacterias___6': 'tipos_bacterias_stenotrophomonas_maltophilia',
        'tipos_bacterias___7': 'tipos_bacterias_acinetobacter',
        'tipos_bacterias___8': 'tipos_bacterias_outros',
        'qual_complicacao___1': 'qual_complicacao_neurologico',
        'qual_complicacao___2': 'qual_complicacao_respiratorio',
        'qual_complicacao___3': 'qual_complicacao_cardiovascular_hemodinamico',
        'qual_complicacao___4': 'qual_complicacao_abdominal',
        'qual_complicacao___5': 'qual_complicacao_renal_endocrino_metabolico_hidroeletrolitico',
        'qual_complicacao___6': 'qual_complicacao_hematologia_hepatologia',
        'qual_complicacao___7': 'qual_complicacao_sepse_choque',
        'qual_complicacao___8': 'qual_complicacao_obstetrica',
        'complicacao_neurologica___1': 'complicacao_neurologica_avc_isquemico',
        'complicacao_neurologica___2': 'complicacao_neurologica_avc_hemorragico_hsa_hsd_hed_hip',
        'complicacao_neurologica___3': 'complicacao_neurologica_infecção_no_snc',
        'complicacao_neurologica___4': 'complicacao_neurologica_crise_convulsiva_ou_epilepsia',
        'complicacao_neurologica___5': 'complicacao_neurologica_trombose_venosa_snc',
        'complicacao_neurologica___6': 'complicacao_neurologica_agitação_delirium',
        'complicacao_neurologica___7': 'complicacao_neurologica_encefalopatia',
        'complicacao_neurologica___8': 'complicacao_neurologica_pos_isquemico_anoxica',
        'complicacao_neurologica___9': 'complicacao_neurologica_outras',
        'complicacao_neurologica___10': 'complicacao_neurologica_hipertensao_intracraniana',
        'qual_complicacao_resp___1': 'qual_complicacao_resp_infecçao',
        'qual_complicacao_resp___2': 'qual_complicacao_resp_insuficiencia_respiratoria',
        'qual_complicacao_resp___3': 'qual_complicacao_resp_lesao_pleural',
        'qual_complicacao_resp___4': 'qual_complicacao_resp_edema_de_glote',
        'qual_complicacao_resp___5': 'qual_complicacao_resp_atelectasia',
        'qual_complicacao_resp___6': 'qual_complicacao_resp_tep',
        'qual_complicacao_resp___7': 'qual_complicacao_resp_eap_icc_has_congestao_pulmonar',
        'qual_complicacao_resp___8': 'qual_complicacao_resp_hemoptise',
        'qual_complicacao_resp___9': 'qual_complicacao_resp_outros',
        'complicacao_respiratoria_infec___1': 'complicacao_respiratoria_infec_pneumonia_nosocomial',
        'complicacao_respiratoria_infec___2': 'complicacao_respiratoria_infec_traqueobronquite',
        'complicacao_respiratoria_infec___3': 'complicacao_respiratoria_infec_empiema',
        'complicacao_respiratoria_infec___4': 'complicacao_respiratoria_infec_outros',
        'compli_respiratoria_insuf___1': 'compli_respiratoria_insuf_broncoespasmo',
        'compli_respiratoria_insuf___2': 'compli_respiratoria_insuf_dpoc_exacerbado_nao_infeccioso',
        'compli_respiratoria_insuf___3': 'compli_respiratoria_insuf_asma_descompensada',
        'compli_respiratoria_insuf___4': 'compli_respiratoria_insuf_sara',
        'compli_resp_lesao_pleural___1': 'compli_resp_lesao_pleural_derrame_pleural',
        'compli_resp_lesao_pleural___2': 'compli_resp_lesao_pleural_hemotorax',
        'compli_resp_lesao_pleural___3': 'compli_resp_lesao_pleural_pneumotorax',
        'compli_resp_lesao_pleural___4': 'compli_resp_lesao_pleural_outros',
        'qual_complicacao_cardio___1': 'qual_complicacao_cardio_isquemia_miocardica',
        'qual_complicacao_cardio___2': 'qual_complicacao_cardio_choque',
        'qual_complicacao_cardio___3': 'qual_complicacao_cardio_pcr',
        'qual_complicacao_cardio___4': 'qual_complicacao_cardio_arritmias',
        'qual_complicacao_cardio___5': 'qual_complicacao_cardio_icc',
        'qual_complicacao_cardio___6': 'qual_complicacao_cardio_oclusao_arterial',
        'qual_complicacao_cardio___7': 'qual_complicacao_cardio_tvp',
        'qual_complicacao_cardio___8': 'qual_complicacao_cardio_outros',
        'compli_cardio_isquemia___1': 'compli_cardio_isquemia_iamcsst',
        'compli_cardio_isquemia___2': 'compli_cardio_isquemia_iamssst',
        'compli_cardio_isquemia___3': 'compli_cardio_isquemia_angina_s_iam',
        'compli_cardio_isquemia___4': 'compli_cardio_isquemia_outros',
        'compli_cardio_choque___1': 'compli_cardio_choque_hipovolemico_hemorragico',
        'compli_cardio_choque___2': 'compli_cardio_choque_distributivo_inflamatorio',
        'compli_cardio_choque___3': 'compli_cardio_choque_distributivo_septico',
        'compli_cardio_choque___4': 'compli_cardio_choque_distributivo_anafilatico',
        'compli_cardio_choque___5': 'compli_cardio_choque_distributivo_neurogenico',
        'compli_cardio_choque___6': 'compli_cardio_choque_obstrutivo_tep_maciço',
        'compli_cardio_choque___7': 'compli_cardio_choque_obstrutivo_tamponamento_cardiaco',
        'compli_cardio_choque___8': 'compli_cardio_choque_obstrutivo_pneumotorax',
        'compli_cardio_choque___9': 'compli_cardio_choque_cardiogenico',
        'compli_cardio_arritmias___1': 'compli_cardio_arritmias_bradiarritmias',
        'compli_cardio_arritmias___2': 'compli_cardio_arritmias_taquiarritmias_arritmias',
        'qual_complicacao_abdominal___1': 'qual_complicacao_abdominal_abdomen_agudo',
        'qual_complicacao_abdominal___2': 'qual_complicacao_abdominal_hemorragia_digestiva',
        'compli_abdominal_agudo___1': 'compli_abdominal_agudo_pancreatite',
        'compli_abdominal_agudo___2': 'compli_abdominal_agudo_vias_biliares',
        'compli_abdominal_agudo___3': 'compli_abdominal_agudo_apendicite',
        'compli_abdominal_agudo___4': 'compli_abdominal_agudo_diverticulite',
        'compli_abdominal_agudo___5': 'compli_abdominal_agudo_geca',
        'compli_abdominal_agudo___6': 'compli_abdominal_agudo_outros_inflamatorio_infeccioso',
        'compli_abdominal_agudo___7': 'compli_abdominal_agudo_perfurativo',
        'compli_abdominal_agudo___8': 'compli_abdominal_agudo_oclusivo',
        'compli_abdominal_agudo___9': 'compli_abdominal_agudo_isquemia_mesenterica',
        'compli_abdominal_agudo___10': 'compli_abdominal_agudo_outros',
        'compli_abdominal_agudo___11': 'compli_abdominal_agudo_compartimentaçao_abdominal',
        'compli_abdominal_hemorragia___1': 'compli_abdominal_hemorragia_hda',
        'compli_abdominal_hemorragia___2': 'compli_abdominal_hemorragia_hdb',
        'qual_complicacao_renal___1': 'qual_complicacao_renal_itu',
        'qual_complicacao_renal___2': 'qual_complicacao_renal_pielonefrite',
        'qual_complicacao_renal___3': 'qual_complicacao_renal_ira',
        'qual_complicacao_renal___4': 'qual_complicacao_renal_rabdomiolise',
        'qual_complicacao_renal___5': 'qual_complicacao_renal_outros_disturbios_hidroeletrolitcos',
        'qual_complicacao_renal___6': 'qual_complicacao_renal_cetoacidose_diabética_estado_hiperosmolar',
        'qual_complicacao_renal___7': 'qual_complicacao_renal_outros_disturbios_endocrino_e_metabolicos',
        'qual_complicacao_renal___8': 'qual_complicacao_renal_outros',
        'compli_renal_ira___1': 'ira_primaria',
        'compli_renal_ira___2': 'compli_renal_ira_drc_agudizada',
        'compli_renal_ira___3': 'compli_renal_ira_emergencia_dialitica_anemia',
        'qual_complicacao_hematologia___1': 'qual_complicacao_hematologia_anemia',
        'qual_complicacao_hematologia___2': 'qual_complicacao_hematologia_plaquetopenia',
        'qual_complicacao_hematologia___3': 'qual_complicacao_hematologia_neutropenia',
        'qual_complicacao_hematologia___4': 'qual_complicacao_hematologia_pancitopenia',
        'qual_complicacao_hematologia___5': 'qual_complicacao_hematologia_disturbios_da_coagulaçao',
        'qual_complicacao_hematologia___6': 'qual_complicacao_hematologia_hepatite_aguda',
        'qual_complicacao_hematologia___7': 'qual_complicacao_hematologia_insuficiencia_hepatica_aguda',
        'qual_complicacao_hematologia___8': 'qual_complicacao_hematologia_outros',
        'qual_complicacao_sepse___1': 'qual_complicacao_sepse_subgrupo_sepse_foco',
        'qual_complicacao_sepse___2': 'qual_complicacao_sepse_subgrupo_sepse_disfunçoes',
        'compli_sepse_foco___1': 'compli_sepse_foco_neurologico',
        'compli_sepse_foco___2': 'compli_sepse_foco_respiratorio',
        'compli_sepse_foco___3': 'compli_sepse_foco_abdominal',
        'compli_sepse_foco___4': 'compli_sepse_foco_itu',
        'compli_sepse_foco___5': 'compli_sepse_foco_corrente_sanguinea',
        'compli_sepse_foco___6': 'compli_sepse_foco_partes_moles',
        'compli_sepse_foco___7': 'compli_sepse_foco_indeterminado',
        'compli_sepse_foco___8': 'compli_sepse_foco_outros',
        'compli_sepse_foco_neuro___1': 'compli_sepse_foco_neuro_meningite',
        'compli_sepse_foco_neuro___2': 'compli_sepse_foco_neuro_encefalite',
        'compli_sepse_foco_neuro___3': 'compli_sepse_foco_neuro_ventriculite',
        'compli_sepse_foco_neuro___4': 'compli_sepse_foco_neuro_abcesso',
        'compli_sepse_foco_neuro___5': 'compli_sepse_foco_neuro_outras',
        'compli_sepse_foco_resp___1': 'compli_sepse_foco_resp_pneumonia_comunitaria',
        'compli_sepse_foco_resp___2': 'compli_sepse_foco_resp_pneumonia_nosocomial',
        'compli_sepse_foco_resp___3': 'compli_sepse_foco_resp_dpoc',
        'compli_sepse_foco_resp___4': 'compli_sepse_foco_resp_pneumonite_viral',
        'compli_sepse_foco_resp___5': 'compli_sepse_foco_resp_traqueobronquite',
        'compli_sepse_foco_resp___6': 'compli_sepse_foco_resp_empiema',
        'compli_sepse_foco_resp___7': 'compli_sepse_foco_resp_outros',
        'compli_sepse_foco_abdominal___1': 'compli_sepse_foco_abdominal_pancreatite',
        'compli_sepse_foco_abdominal___2': 'compli_sepse_foco_abdominal_apendicite',
        'compli_sepse_foco_abdominal___3': 'compli_sepse_foco_abdominal_diverticulite',
        'compli_sepse_foco_abdominal___4': 'compli_sepse_foco_abdominal_geca',
        'compli_sepse_foco_abdominal___5': 'compli_sepse_foco_abdominal_outros_inflamatorio_infeccioso',
        'compli_sepse_foco_abdominal___6': 'compli_sepse_foco_abdominal_perfurativo',
        'compli_sepse_foco_abdominal___7': 'compli_sepse_foco_abdominal_oclusivo',
        'compli_sepse_foco_abdominal___8': 'compli_sepse_foco_abdominal_isquemia_mesenterica',
        'compli_sepse_foco_abdominal___9': 'compli_sepse_foco_abdominal_outros',
        'compli_sepse_foco_itu___1': 'compli_sepse_foco_itu_itu',
        'compli_sepse_foco_itu___2': 'compli_sepse_foco_itu_pielonefrite',
        'compli_sepse_foco_corrente_sangue___1': 'compli_sepse_foco_corrente_sangue_endocardite',
        'compli_sepse_foco_corrente_sangue___2': 'compli_sepse_foco_corrente_sangue_infecção_relacionado_a_cvc',
        'compli_sepse_disfuncao___1': 'compli_sepse_disfuncao_neurologico',
        'compli_sepse_disfuncao___2': 'compli_sepse_disfuncao_respiratorio',
        'compli_sepse_disfuncao___3': 'compli_sepse_disfuncao_hemodinamica',
        'compli_sepse_disfuncao___4': 'compli_sepse_disfuncao_renal',
        'compli_sepse_disfuncao___5': 'compli_sepse_disfuncao_plaquetopenia',
        'compli_sepse_disfuncao___6': 'compli_sepse_disfuncao_hiperbilirrubinemia',
        'compli_sepse_disfun_hemo___1': 'compli_sepse_disfun_hemo_hiperlactatemia',
        'compli_sepse_disfun_hemo___2': 'compli_sepse_disfun_hemo_choque',
        'complicacao_obstetrica___1': 'complicacao_obstetrica_sindrome_hellp',
        'complicacao_obstetrica___2': 'complicacao_obstetrica_pre_eclanpsia',
        'complicacao_obstetrica___3': 'complicacao_obstetrica_eclanpsia',
        'complicacao_obstetrica___4': 'complicacao_obstetrica_embolia_de_liquido_amniotico',
        'complicacao_obstetrica___5': 'complicacao_obstetrica_descolamento_prematuro_de_placenta',
        'complicacao_obstetrica___6': 'complicacao_obstetrica_esteatose_hepatica_da_gestaçao',
        'complicacao_obstetrica___7': 'complicacao_obstetrica_diabetes_gestacional',
        'complicacao_obstetrica___8': 'complicacao_obstetrica_civd',
        'complicacao_obstetrica___9': 'complicacao_obstetrica_outros',
        'grupos_desfecho___1': 'grupos_desfecho_neurologico',
        'grupos_desfecho___2': 'grupos_desfecho_respiratorio',
        'grupos_desfecho___3': 'grupos_desfecho_cardiovascular_hemodinamico',
        'grupos_desfecho___4': 'grupos_desfecho_abdominal',
        'grupos_desfecho___5': 'grupos_desfecho_endocrino_metabolico_hidroeletrolitico',
        'grupos_desfecho___6': 'grupos_desfecho_renal_urologia',
        'grupos_desfecho___7': 'grupos_desfecho_hematologia',
        'grupos_desfecho___8': 'grupos_desfecho_sepse_choque_septico',
        'grupos_desfecho___9': 'grupos_desfecho_trauma',
        'grupos_desfecho___10': 'grupos_desfecho_cabeça_pescoço_ortopedia',
        'grupos_desfecho___11': 'grupos_desfecho_ginecologia_e_obstetricia',
        'grupos_desfecho___12': 'grupos_desfecho_intoxicaçao_exogena',
        'sub_grupo_neuro_desfe___1': 'sub_grupo_neuro_desfe_avc',
        'sub_grupo_neuro_desfe___2': 'sub_grupo_neuro_desfe_infecçao',
        'sub_grupo_neuro_desfe___3': 'sub_grupo_neuro_desfe_hsa',
        'sub_grupo_neuro_desfe___4': 'sub_grupo_neuro_desfe_hsd',
        'sub_grupo_neuro_desfe___5': 'sub_grupo_neuro_desfe_hed',
        'sub_grupo_neuro_desfe___6': 'sub_grupo_neuro_desfe_crise_convulsiva_ou_epilepsia',
        'sub_grupo_neuro_desfe___7': 'sub_grupo_neuro_desfe_trombose_venosa_snc',
        'sub_grupo_neuro_desfe___8': 'sub_grupo_neuro_desfe_neoplasia',
        'sub_grupo_neuro_desfe___9': 'sub_grupo_neuro_desfe_neuromuscular',
        'sub_grupo_neuro_desfe___10': 'sub_grupo_neuro_desfe_delirium',
        'sub_grupo_neuro_desfe___11': 'sub_grupo_neuro_desfe_encefalopatia_nao_especifica_rnc',
        'sub_grupo_neuro_desfe___12': 'sub_grupo_neuro_desfe_lesao_hipoxico_isquemica_pos_pcr',
        'sub_grupo_neuro_desfe___13': 'sub_grupo_neuro_desfe_lesao_medular',
        'sub_grupo_neuro_desfe___14': 'sub_grupo_neuro_desfe_epilepsia',
        'sub_grupo_neuro_desfe___15': 'sub_grupo_neuro_desfe_pos_operatorio',
        'sub_grupo_neuro_desfe___16': 'sub_grupo_neuro_desfe_outros',
        'sub_grupo_resp_desfe___1': 'sub_grupo_resp_desfe_infecçao',
        'sub_grupo_resp_desfe___2': 'sub_grupo_resp_desfe_dpoc_descompensado',
        'sub_grupo_resp_desfe___3': 'sub_grupo_resp_desfe_asma_descompensada',
        'sub_grupo_resp_desfe___4': 'sub_grupo_resp_desfe_sara',
        'sub_grupo_resp_desfe___5': 'sub_grupo_resp_desfe_broncoaspiraçao',
        'sub_grupo_resp_desfe___6': 'sub_grupo_resp_desfe_lesao_pleural',
        'sub_grupo_resp_desfe___7': 'sub_grupo_resp_desfe_edema_de_glote',
        'sub_grupo_resp_desfe___8': 'sub_grupo_resp_desfe_atelectasia',
        'sub_grupo_resp_desfe___9': 'sub_grupo_resp_desfe_tep',
        'sub_grupo_resp_desfe___10': 'sub_grupo_resp_desfe_eap_edema_agudo_hipertensivo_congestao_pulmonar',
        'sub_grupo_resp_desfe___11': 'sub_grupo_resp_desfe_hemoptise',
        'sub_grupo_resp_desfe___12': 'sub_grupo_resp_desfe_insuficiencia_respiratoria_de_causa_neuromuscular',
        'sub_grupo_resp_desfe___13': 'sub_grupo_resp_desfe_pos_operatorio_toracico',
        'sub_grupo_resp_desfe___14': 'sub_grupo_resp_desfe_outros',
        'sub_grupo_cardio_desfe___1': 'sub_grupo_cardio_desfe_isquemia_miocardica',
        'sub_grupo_cardio_desfe___2': 'sub_grupo_cardio_desfe_insuficiencia_cardiaca',
        'sub_grupo_cardio_desfe___3': 'sub_grupo_cardio_desfe_arritmias',
        'sub_grupo_cardio_desfe___4': 'sub_grupo_cardio_desfe_doenças_da_aorta',
        'sub_grupo_cardio_desfe___5': 'sub_grupo_cardio_desfe_oclusao_arterial',
        'sub_grupo_cardio_desfe___6': 'sub_grupo_cardio_desfe_tvp',
        'sub_grupo_cardio_desfe___7': 'sub_grupo_cardio_desfe_pos_pcr_de_causa_indefinida',
        'sub_grupo_cardio_desfe___8': 'sub_grupo_cardio_desfe_pos_operatorio_cardiovascular',
        'sub_grupo_cardio_desfe___9': 'sub_grupo_cardio_desfe_tamponamento_cardiaco',
        'sub_grupo_cardio_desfe___10': 'sub_grupo_cardio_desfe_choque_cardiogenico',
        'sub_grupo_cardio_desfe___11': 'sub_grupo_cardio_desfe_outros',
        'sub_grupo_abd_desfe___1': 'sub_grupo_abd_desfe_abdomen_agudo',
        'sub_grupo_abd_desfe___2': 'sub_grupo_abd_desfe_geca',
        'sub_grupo_abd_desfe___3': 'sub_grupo_abd_desfe_hemorragia_digestiva',
        'sub_grupo_abd_desfe___4': 'sub_grupo_abd_desfe_hepatologia',
        'sub_grupo_abd_desfe___5': 'sub_grupo_abd_desfe_pos_operatorio_eletivo_de_cirurgia_abdominal',
        'sub_grupo_endo_desfe___1': 'sub_grupo_endo_desfe_disturbio_eletrolitico',
        'sub_grupo_endo_desfe___2': 'sub_grupo_endo_desfe_cetoacidose_diabetica',
        'sub_grupo_endo_desfe___3': 'sub_grupo_endo_desfe_estado_hiperosmolar',
        'sub_grupo_endo_desfe___4': 'sub_grupo_endo_desfe_crise_tireotoxica',
        'sub_grupo_endo_desfe___5': 'sub_grupo_endo_desfe_outros_disturbios_endocrinos_e_metabolicos',
        'sub_grupo_renal_uru_desfe___1': 'sub_grupo_renal_uru_desfe_infecçao',
        'sub_grupo_renal_uru_desfe___2': 'sub_grupo_renal_uru_desfe_ira',
        'sub_grupo_renal_uru_desfe___3': 'sub_grupo_renal_uru_desfe_rabdomiolise',
        'sub_grupo_renal_uru_desfe___4': 'sub_grupo_renal_uru_desfe_nefrolitiase',
        'sub_grupo_renal_uru_desfe___5': 'sub_grupo_renal_uru_desfe_pos_operatorio',
        'sub_grupo_hema_desfe___1': 'sub_grupo_hema_desfe_anemia',
        'sub_grupo_hema_desfe___2': 'sub_grupo_hema_desfe_plaquetopenia',
        'sub_grupo_hema_desfe___3': 'sub_grupo_hema_desfe_neutropenia',
        'sub_grupo_hema_desfe___4': 'sub_grupo_hema_desfe_pancitopenia',
        'sub_grupo_hema_desfe___5': 'sub_grupo_hema_desfe_leucemia_linfoma',
        'sub_grupo_hema_desfe___6': 'sub_grupo_hema_desfe_disturbios_da_coagulaçao',
        'sub_grupo_hema_desfe___7': 'sub_grupo_hema_desfe_outros',
        'sub_grupo_sep_foco_desfe___1': 'sub_grupo_sep_foco_desfe_neurologico',
        'sub_grupo_sep_foco_desfe___2': 'sub_grupo_sep_foco_desfe_respiratorio',
        'sub_grupo_sep_foco_desfe___3': 'sub_grupo_sep_foco_desfe_abdominal',
        'sub_grupo_sep_foco_desfe___4': 'sub_grupo_sep_foco_desfe_urinario',
        'sub_grupo_sep_foco_desfe___5': 'sub_grupo_sep_foco_desfe_corrente_sanguinea',
        'sub_grupo_sep_foco_desfe___6': 'sub_grupo_sep_foco_desfe_partes_moles',
        'sub_grupo_sep_foco_desfe___7': 'sub_grupo_sep_foco_desfe_indeterminado',
        'sub_grupo_sep_foco_desfe___8': 'sub_grupo_sep_foco_desfe_outros',
        'sub_grupo_sepse_disfun_desfe___1': 'sub_grupo_sepse_disfun_desfe_neurologico',
        'sub_grupo_sepse_disfun_desfe___2': 'sub_grupo_sepse_disfun_desfe_respiratorio',
        'sub_grupo_sepse_disfun_desfe___3': 'sub_grupo_sepse_disfun_desfe_hemodinamica',
        'sub_grupo_sepse_disfun_desfe___4': 'sub_grupo_sepse_disfun_desfe_renal',
        'sub_grupo_sepse_disfun_desfe___5': 'sub_grupo_sepse_disfun_desfe_plaquetopenia',
        'sub_grupo_sepse_disfun_desfe___6': 'sub_grupo_sepse_disfun_desfe_hiperbilirrubinemia',
        'sub_grupo_trau_les_desfe___1': 'sub_grupo_trau_les_desfe_tce',
        'sub_grupo_trau_les_desfe___2': 'sub_grupo_trau_les_desfe_trm',
        'sub_grupo_trau_les_desfe___3': 'sub_grupo_trau_les_desfe_fx_vertebral_sem_trm',
        'sub_grupo_trau_les_desfe___4': 'sub_grupo_trau_les_desfe_face_cervical',
        'sub_grupo_trau_les_desfe___5': 'sub_grupo_trau_les_desfe_cardiaca',
        'sub_grupo_trau_les_desfe___6': 'sub_grupo_trau_les_desfe_toracica',
        'sub_grupo_trau_les_desfe___7': 'sub_grupo_trau_les_desfe_abdominal_pelvico',
        'sub_grupo_trau_les_desfe___8': 'sub_grupo_trau_les_desfe_extremidades',
        'sub_grupo_trau_les_desfe___9': 'sub_grupo_trau_les_desfe_embolia_gordurosa',
        'sub_grupo_trau_mecan_desfe___1': 'sub_grupo_trau_mecan_desfe_colisoes',
        'sub_grupo_trau_mecan_desfe___2': 'sub_grupo_trau_mecan_desfe_queda_de_outro_nivel',
        'sub_grupo_trau_mecan_desfe___3': 'sub_grupo_trau_mecan_desfe_queda_de_mesmo_nivel',
        'sub_grupo_trau_mecan_desfe___4': 'sub_grupo_trau_mecan_desfe_atropelamento',
        'sub_grupo_trau_mecan_desfe___5': 'sub_grupo_trau_mecan_desfe_agressao_faf_fab',
        'sub_grupo_trau_mecan_desfe___6': 'sub_grupo_trau_mecan_desfe_queimaduras_choque_eletrico',
        'sub_grupo_trau_mecan_desfe___7': 'sub_grupo_trau_mecan_desfe_lesao_autoinfligida',
        'sub_grupo_cab_orto_desfe___1': 'sub_grupo_cab_orto_desfe_pos_operatorio_cabeça_e_pescoço',
        'sub_grupo_cab_orto_desfe___2': 'sub_grupo_cab_orto_desfe_pos_operatorio_eletivo_ortopedia',
        'sub_grupo_gine_desfe___1': 'sub_grupo_gine_desfe_sindrome_hellp',
        'sub_grupo_gine_desfe___2': 'sub_grupo_gine_desfe_pre_eclampsia',
        'sub_grupo_gine_desfe___3': 'sub_grupo_gine_desfe_eclampsia',
        'sub_grupo_gine_desfe___4': 'sub_grupo_gine_desfe_embolia_de_liquido_amniotico',
        'sub_grupo_gine_desfe___5': 'sub_grupo_gine_desfe_descolamento_prematuro_de_placenta',
        'sub_grupo_gine_desfe___6': 'sub_grupo_gine_desfe_esteatose_hepatica_da_gestaçao',
        'sub_grupo_gine_desfe___7': 'sub_grupo_gine_desfe_diabetes_gestacional',
        'sub_grupo_gine_desfe___8': 'sub_grupo_gine_desfe_civd',
        'sub_grupo_gine_desfe___9': 'sub_grupo_gine_desfe_cirurgias_ginecologicas',
        'sub_grupo_gine_desfe___10': 'sub_grupo_gine_desfe_outros',
        'sub_grupo_intoxi_exo_desfe___1': 'sub_grupo_intoxi_exo_desfe_ansiolitico',
        'sub_grupo_intoxi_exo_desfe___2': 'sub_grupo_intoxi_exo_desfe_antidepressivos',
        'sub_grupo_intoxi_exo_desfe___3': 'sub_grupo_intoxi_exo_desfe_antipsicoticos',
        'sub_grupo_intoxi_exo_desfe___4': 'sub_grupo_intoxi_exo_desfe_alcool',
        'sub_grupo_intoxi_exo_desfe___5': 'sub_grupo_intoxi_exo_desfe_drogas_ilicitas',
        'sub_grupo_intoxi_exo_desfe___6': 'sub_grupo_intoxi_exo_desfe_organofosforados',
        'sub_grupo_intoxi_exo_desfe___7': 'sub_grupo_intoxi_exo_desfe_outros',
    }  # Preencha com os nomes corretos, se necessário

    if novo_nome_colunas:
        df.rename(columns = novo_nome_colunas, inplace = True)

    df.replace({'Checked':'Sim', 'Unchecked':'Não'}, inplace = True)

    if exclusao_colunas:
        df.drop(columns = exclusao_colunas, inplace = True)

    transform(df, colunas_a_preencher)

    criar_coluna_mesclada(df, colunas_a_preencher, 'uti_combined')

    criar_coluna_mesclada(df, ['data_hora_obito', 'data_hora_alta'], 'data_hora_final')

    criar_coluna_mesclada(df, ['tempo_internamento_obito', 'tempo_internamento_alta'], 'tempo_internamento_final')

    df ['data_nascimento'] = pd.to_datetime(df ['data_nascimento'], errors = 'coerce')

    df ['idade'] = df ['data_nascimento'].apply(calcular_idade)

    df ['data_internamento'] = pd.to_datetime(df ['data_internamento'], format = '%Y-%m-%d %H:%M', errors = 'coerce')

    df ['data_hora_final'] = pd.to_datetime(df ['data_hora_final'], format = '%Y-%m-%d %H:%M', errors = 'coerce')

    # Preencher 'data_hora_final' com a data atual onde necessário
    preencher_data_hora_final(df)

    # Criar a nova coluna 'data_ajustada' com a diferença entre as datas em dias
    calcular_data_ajustada(df)

    # Aplicar a função split_admissions ao DataFrame
    df = split_admissions(df)

    # Salvar o DataFrame no arquivo de saída
    df.to_csv(caminho_saida, index = False)


if __name__ == "__main__":
    colunas_excluir = [
        'perspectiva_alta_defender',
        'disfuncoes_defender___1',
        'disfuncoes_defender___2',
        'disfuncoes_defender___3',
        'disfuncoes_defender___4',
        'diag_drc_defender',
        'adm_plan_cx_defender',
        'inibidor_slgt2_defender',
        'jejum_defender',
        'criterio_maior_24_defender',
        "resumo_alta",
        "resumo_obito"
    ]
    renomear_colunas_e_salvar('dados.csv', 'data_work.csv', colunas_excluir)
